### ISSUE TITLE
After a step is created, clear input box?

### ISSUE THREAD

**Issue by raghubetina** [jelaniwoods/msm-theater#12]
Right now, after I save a Step, I have to then manually delete out the value from the input before I can type my next Step.

![clear input after step](https://user-images.githubusercontent.com/811217/70698647-310a0a80-1cc8-11ea-8b9c-8547364bc005.gif)

How about clearing the input after a Step is saved? (But still pre-populating it with the prior query when not saving a Step.)

**Comment by jelaniwoods** [comment]
This should be fixed in [this commit](https://github.com/jelaniwoods/msm-theater/commit/10ef40dac99ab11eb02a16353bf3e08b07e8360b)
