### ISSUE TITLE
Unclear on how to use Steps

### ISSUE THREAD

**Issue by raghubetina** [jelaniwoods/msm-theater#13]
I don't think I quite understand the concept of a Step. Here's what I thought it allowed:

<img width="1792" alt="Screen Shot 2019-12-12 at 10 15 26 AM" src="https://user-images.githubusercontent.com/811217/70698755-63b40300-1cc8-11ea-962e-6d89b182e02a.png">

What is the intended usage?

**Comment by jelaniwoods** [comment]
Potentially fixed in [this commit](https://github.com/jelaniwoods/msm-theater/commit/072376c068469f0d730185126ed995ab264e397d). I've made it so, "Execute" will run any of the steps too if a step already exists. Previously, to run all of the steps, you needed to click on "Step".
