### ISSUE TITLE
Level 2: Not sure why my query isn't passing

### ISSUE THREAD

**Issue by raghubetina** [jelaniwoods/msm-theater#14]
The task is:

> Return the record of the Director who directed The Shawshank Redemption.

This is my query:

```
Director.find(Movie.find_by(title: "The Shawshank Redemption").director_id)
```

I think it ought to work? But it's not showing me the button to proceed:

<img width="1792" alt="Screen Shot 2019-12-12 at 10 21 03 AM" src="https://user-images.githubusercontent.com/811217/70699249-1f753280-1cc9-11ea-9933-c44fd971eaf7.png">

**Comment by jelaniwoods** [comment]
Nice catch! I forgot to update the method that checks for correctness to not use the query with the spaces taken out.

**Comment by jelaniwoods** [comment]
Should be fixed [here](https://github.com/jelaniwoods/msm-theater/commit/2e3a470b719ba8d76a2fa29190b3e5be7b6c3b6a#)
